# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/models/lenet
Accept: application/json

###

PUT http://127.0.0.1:8000/items/1
Accept: application/json

###

GET http://127.0.0.1:8000/docs
Accept: application/json